#path = '/Users/gdelimpaltadak/Desktop/Material/Code/Python/Isoc_Manifolds_Tool/SMT_files'
path = '/Users/gmaddodi/Desktop/Isoc_Manifolds_Tool/SMT_files'
#dreal_path = '/Users/gdelimpaltadak/dReal-3.16.06.02-darwin/bin/dReal'
dreal_path = '/Users/gmaddodi/dreal4/bazel-bin/dreal/dreal'
#dreach_path = '/Users/gdelimpaltadak/dReal-3.16.06.02-darwin/bin/dReach'
dreach_path = '/Users/gmaddodi/dreal3-master/bin/dReach'
#flowstar_path = '/Users/gdelimpaltadak/Downloads/flowstar-2.0.0/flowstar'
flowstar_path = '/Users/gmaddodi/flowstar/flowstar-2.0.0/flowstar'