from ETCetera.util.construct_from_file_linearPETC import construct_linearPETC_traffic_from_file
from ETCetera.util.construct_from_file_nonlinearETC import construct_nonlinearETC_traffic_from_file
from ETCetera.util import parsing
from ETCetera.util.homogeneous import test_homogeneity, make_homogeneous, make_homogeneous_etc